spring.application.name=firmplus
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/firmplus
spring.datasource.username=Admin